name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest # Беремо віртуальний Linux

    steps:
    # 1. Забираємо твій код
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Встановлюємо Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 3. Встановлюємо залежності
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Запускаємо тести
    # Оскільки ми використовуємо SQLite в пам'яті для тестів (conftest.py),
    # нам не треба піднімати окремий сервіс Postgres тут. Це спрощує CI.
    - name: Run Tests with Pytest
      run: |
        pytest -v